name: "rė`dŭkt"
description: "product lifecycle, extended team management; uncomplicated!"

author: "Bagwan Pankaj"

url: "http://m3xm.github.io"
baseurl: ""#/hikari-for-Jekyll

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: .bagwanpankaj.com
ga_tracking_id: UA-47727049-1
